### ISSUE TITLE
[Mod Compat] <Visual Workbench - Fabric (LunaPixelStudios)>

### ISSUE THREAD

**Issue by KaiOrCurtt** [xanthian/variantcraftingtables#14]
Hey, hope you're well. I'm really enjoying this mod, I was wondering if it's possible to configure compatibility with the Visual Workbench mod for 1.18.2+? As it stands, the variant crafting tables aren't compatible with it. Any information is appreciated as I'm not very knowledgeable in the modding scene.

**Comment by xanthian** [comment]
I shall take a look and let you know :)

**Comment by xanthian** [comment]
On the mod page he says this :

**Q:** Does this work with crafting tables from other mods?
**A:** Not at all on Fabric due to technical limitations, but for the most part on Forge where support has to be manually enabled. Many modded crafting tables are enabled by default, those that are not can be added to a custom config file found at .minecraft/config/visual_workbench.json (not accessible from in-game). if you add a crafting table yourself and it doesn't work it is likely incompatible with this mod.


Presumably you tried the config thing?
I'll drop them a message if it doesnt work to see what I need to do.

**Comment by KaiOrCurtt** [comment]
Thanks for the response, yeah i checked that out. but i wasn’t exactly sure
what to do with the menu. so i was pretty confused. because of the config
i’m pretty sure it’s not a compatibility issue as long as it works
properly, since they said there’s a possibility it just won’t work.

in other words, i wasn’t sure what to add to the config. Any ideas?

**Comment by xanthian** [comment]
A: Not at all on Fabric due to technical limitations

it doesnt work on fabric at all apparently.
nothing I can do im afraid.

**Comment by KaiOrCurtt** [comment]
Ah i understand, just wanted to get more confirmation on their statements.
thanks so much!
